---
name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
      - name: Build project
        run: dotnet build

  publish:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        runtime: ["linux-x64", "osx-arm64", "osx-x64", "win-x64"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
      - name: Build project binary
        run: dotnet publish --runtime ${{matrix.runtime}}

      - name: "Get current date"
        run: echo "TODAY=$(date +'%Y_%m_%d')" >> $GITHUB_ENV

      - name: "Get short SHA"
        run: echo "SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: "Set release version"
        run: echo "version=${{env.TODAY}}_${{matrix.runtime}}_${{env.SHORT_SHA}} >> $GITHUB_OUTPUT"
        id: "version"

      - name: "Create release"
        uses: "actions/create-release@v1"
        id: "create_release"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        with:
          draft: false
          prerelease: false
          release_name: "${{ steps.version.outputs.version }}"
          tag_name: "${{env.SHA_SHORT}}_${{matrix.version}}"

      - name: "Upload artifacts to release"
        uses: "actions/upload-release-asset@v1" # NOTE: this action is deprecated
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        with:
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
          asset_path: "./bin/Release/net8.0/${{matrix.runtime}}/publish/ice-cdr${{(startsWith(matrix.runtime, 'win') && '.exe') || ''}}"
          asset_name: "ice-cdr${{ (startsWith(matrix.runtime, 'win') && '.exe') || '' }}"
          asset_content_type: "application/octet-stream" # TODO: verify that this is the correct type
